#this will test the ability to randomly genrate letter combinations


import json
import random
import sys

def makeName(mode):
    #Load the starting dicitionary
    #mode must be MN/FN + letter/pair/triple
    startDict  = toDict(mode +'Freq.txt')
    followDict = toDict(mode +'s.txt')

    #get a list of the starter keys, and a list of probabilities
    startkeys = list(startDict.keys())
    startprobs = list(startDict.values())

    #randomly generate a unit, call it curr
    curr = random.choices(startkeys, weights=startprobs, k = 1)
    #one char so make it a string
    curr = "".join(curr)

    # Add it to the output list
    outstring = []
    outstring.append(curr)

    #---------------------------------------------
    # get list of follower keys and probabilities
    #test
    for i in range(5):
        #get the probability dict of the current value
        if(curr in followDict):
            d = followDict[curr]
        else:
            break
        #split its values and keys
        dkeys = list(d.keys())
        dvalues = list(d.values())

        #use the probabilities to generate the next unit


        

        #convert to string
        next = "".join(next)
        outstring.append(next)

        #update curr to move on
        curr = next

    # Put the whole string together
    outstring = "".join(outstring)
    outstring = cleanUp(outstring)
    return outstring

#def main():
    #mode = sys.argv[1]
    #for i in range(20):
        #name = makeName(mode)
        #name = cleanUp(name)
        #print(name)

#check if the unit has a newline
def hasNewline(string):
    if("\n" in string):
        return True
    else:
        return False

#cleans up output by removing newlines
def cleanUp(name):
    l = list(name)
    for i in range(len(l)):
        if l[i] == "\n":
            l[i] = ""
    name = "".join(l)
    return name

#converts a file generated by trainer.py into a dict
def toDict(filename):

    #check args
    if not filename:
       print("usage: python test.py <filename>.txt")
       return

    else:
        with open(filename, "r") as file:
            string = list(file.readline())

            for i in range(len(string)):
                if string[i] ==  "'":
                  string[i] = '"'
            string = "".join(string)



            #this should be a dict
            res = json.loads(string)

            file.close()
            return res
#main()

